apiVersion: v1
kind: Service
metadata:
  name: go-crud-service
spec:
  type: NodePort
  # type: ClusterIP
  selector:
    app: go-app
  ports:
    - port: 8080
      # targetPort: 9000
      nodePort: 30000 
      protocol: TCP